apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: charts/sealed-secrets
    repoURL: https://github.com/mlhein/ktest.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true